[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"

[profile.default.rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"

# Fork: Block 17636491 (Multichain exploit)
# forge test --fork-url https://rpc.ankr.com/eth --fork-block-number 17636491
